name: Publish Package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PRIVATE_NPM_TOKEN: ${{ secrets.PRIVATE_NPM_TOKEN }}
#  CODECOV_TOKEN: ${{ secrets.CODECOV_FETCH_PHRASE_TOKEN }}

jobs:
  test:
    runs-on: [self-hosted, linux, X64, general, t3.micro]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          printf "@unipolmovecity:registry=https://npm.deployment.unipolmove.city/repository/npm/\n//npm.deployment.unipolmove.city/repository/npm/:_authToken=NpmToken.${PRIVATE_NPM_TOKEN}" > ~/.npmrc
          yarn
      - run: yarn eslint
      - run: yarn prettier
      - run: yarn test
  #      - run: npx codecov
  publish:
    if: ${{ github.event_name != 'pull_request' }}
    needs: ['test']
    runs-on: [self-hosted, linux, X64, general, t3.micro]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          printf "@unipolmovecity:registry=https://npm.deployment.unipolmove.city/repository/npm/\n//npm.deployment.unipolmove.city/repository/npm/:_authToken=NpmToken.${PRIVATE_NPM_TOKEN}" > ~/.npmrc
          yarn
      - run: |
          yarn publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ env.PRIVATE_NPM_TOKEN }}
